#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/image_geometry:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/assignment4_trackingandfollowing:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/cv_bridge:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/assignment3a_wallfollowingandobstacleavoidance:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/assignment2B_turtlebot3:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel:/opt/ros/noetic:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/apriltag'
export LD_LIBRARY_PATH='/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/image_geometry/lib:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/assignment4_trackingandfollowing/lib:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/cv_bridge/lib:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/assignment3a_wallfollowingandobstacleavoidance/lib:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/assignment2B_turtlebot3/lib:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel/lib:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/apriltag/lib:/usr/local/cuda/lib64'
export PATH='/opt/ros/noetic/bin:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/apriltag/bin:/home/gbbyrd/miniconda3/condabin:/usr/local/cuda/bin:/home/gbbyrd/.local/bin:/home/gbbyrd/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/image_geometry/lib/pkgconfig:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/assignment4_trackingandfollowing/lib/pkgconfig:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/cv_bridge/lib/pkgconfig:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/assignment3a_wallfollowingandobstacleavoidance/lib/pkgconfig:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/assignment2B_turtlebot3/lib/pkgconfig:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/apriltag/lib/pkgconfig'
export PYTHONPATH="/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/image_geometry/lib/python3/dist-packages:$PYTHONPATH"
export ROSLISP_PACKAGE_DIRECTORIES="/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/devel_isolated/image_geometry/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/gbbyrd/Desktop/Code/School/Aue823_Spring22_Team1/catkin_ws/src/vision_opencv/image_geometry:$ROS_PACKAGE_PATH"